## MOLECULAR DESCRIPTORS CALCULATION (3D) - Eg with Mordred

#### 1. Set-up:

In [55]:
## packages to install if required (remove hashtag and run):
#!pip install pysmiles
#!pip install descriptastorus
#!pip install mordred

In [56]:
## import necessary libraries:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from pysmiles import read_smiles

from rdkit import Chem
#from rdkit.Chem import Descriptors
from rdkit.Chem import AllChem, PandasTools

from mordred import Calculator, descriptors

from descriptastorus.descriptors.DescriptorGenerator import MakeGenerator

In [57]:
## export dataframe with substances + SMILES:
smiles_df = pd.read_csv('data/contaminants.csv', delimiter = ";")
smiles_df.head(5)

,name,substance_type,CAS_nb,SMILES,detected
0,carbaryl,insecticide,63-25-2,CNC(=O)OC1=CC=CC2=CC=CC=C21,1
1,chlorpyrifos,insecticide,2921-88-2,CCOP(=S)(OCC)OC1=NC(=C(C=C1Cl)Cl)Cl,1
2,cypermethrine,insecticide,52315-07-8,CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)...,1
3,DDD(2-4),insecticide,72-54-8,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl,1
4,dicofol,insecticide,115-32-2,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)(C(Cl)(Cl)Cl)O)Cl,1

In [58]:
## data cleaning:
print(f"Length of database with NAs: {len(smiles_df.SMILES)}")

if smiles_df.SMILES.isna().sum() > 0:
    smiles_cleaned1 = smiles_df.loc[smiles_df.SMILES.notna()].copy()#smiles_df.dropna() ## remove NAs (cannot compute molecular descriptor if no SMILES structure present)
    print(f"Length of database without NAs (cleaned version): {len(smiles_cleaned1.SMILES)}")
else:
    None

Length of database with NAs: 70
Length of database without NAs (cleaned version): 67

In [59]:
## extract list of molecules from their SMILES:
smiles_list = smiles_cleaned1.SMILES

mol_list = []

for s in smiles_list:
    mol = Chem.MolFromSmiles(s)
    mol_list.append(mol)

In [60]:
## append to df + rename columns with mols to 'molecule'
smiles_cleaned = pd.concat([smiles_cleaned1.reset_index(drop = True), pd.DataFrame(mol_list).reset_index(drop = True)], axis = 1)
smiles_cleaned = smiles_cleaned.rename(columns = {0: "molecule"})
smiles_cleaned

,name,substance_type,CAS_nb,SMILES,detected,molecule
0,carbaryl,insecticide,63-25-2,CNC(=O)OC1=CC=CC2=CC=CC=C21,1,<rdkit.Chem.rdchem.Mol object at 0x17d35af10>
1,chlorpyrifos,insecticide,2921-88-2,CCOP(=S)(OCC)OC1=NC(=C(C=C1Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d35b610>
2,cypermethrine,insecticide,52315-07-8,CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)...,1,<rdkit.Chem.rdchem.Mol object at 0x17d35a490>
3,DDD(2-4),insecticide,72-54-8,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359460>
4,dicofol,insecticide,115-32-2,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)(C(Cl)(Cl)Cl)O)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359e70>
...,...,...,...,...,...,...
62,tramadol,PPCP,27203-92-5,CN(C)C[C@H]1CCCC[C@@]1(C2=CC(=CC=C2)OC)O,0,<rdkit.Chem.rdchem.Mol object at 0x17d4458c0>
63,chloroacetic acid,solvent,79-11-8,C(C(=O)O)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445930>
64,DMSO,solvent,67-68-5,CS(=O)C,0,<rdkit.Chem.rdchem.Mol object at 0x17d4459a0>
65,methanol,solvent,67-56-1,CO,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a10>
66,butyltinTrichloride,other,1118-46-3,CCCC[Sn](Cl)(Cl)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a80>

#### 2. Calculation of molecular descriptors:

In [61]:
## set-up Mordred calculator:
calculator_mordred = Calculator(descriptors, ignore_3D = True)

In [62]:
## calculate molecular descriptors:
md_df = calculator_mordred.pandas(mol_list)

 10%|████▌                                       | 7/67 [00:06<01:59,  2.00s/it]

/Users/ciloesans56/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 31%|█████████████▍                             | 21/67 [00:16<00:30,  1.52it/s]

/Users/ciloesans56/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

100%|███████████████████████████████████████████| 67/67 [00:22<00:00,  2.92it/s]

/Users/ciloesans56/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

In [63]:
## reframe df (error on last line => bug fixed)
df = pd.concat([smiles_cleaned.reset_index(drop = True), pd.DataFrame(md_df).reset_index(drop = True)], axis = 1)
df

,name,substance_type,CAS_nb,SMILES,detected,molecule,ABC,ABCGG,nAcid,nBase,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,carbaryl,insecticide,63-25-2,CNC(=O)OC1=CC=CC2=CC=CC=C21,1,<rdkit.Chem.rdchem.Mol object at 0x17d35af10>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,9.496496,46.853672,201.078979,7.733807,362,21,74.0,85.0,4.694444,3.472222
1,chlorpyrifos,insecticide,2921-88-2,CCOP(=S)(OCC)OC1=NC(=C(C=C1Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d35b610>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,9.677653,50.667067,348.926284,12.031941,612,26,86.0,97.0,8.256944,4.180556
2,cypermethrine,insecticide,52315-07-8,CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)...,1,<rdkit.Chem.rdchem.Mol object at 0x17d35a490>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,10.344674,84.588084,415.074199,8.831366,2244,39,146.0,172.0,10.201389,6.166667
3,DDD(2-4),insecticide,72-54-8,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359460>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,9.675269,50.806847,317.953661,11.355488,603,26,90.0,103.0,6.666667,4.000000
4,dicofol,insecticide,115-32-2,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)(C(Cl)(Cl)Cl)O)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359e70>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,10.165967,54.227403,367.909603,12.686538,744,35,106.0,126.0,8.569444,4.229167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,tramadol,PPCP,27203-92-5,CN(C)C[C@H]1CCCC[C@@]1(C2=CC(=CC=C2)OC)O,0,<rdkit.Chem.rdchem.Mol object at 0x17d4458c0>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,...,9.918425,52.447194,263.188529,5.981557,670,30,96.0,112.0,7.006944,4.291667
63,chloroacetic acid,solvent,79-11-8,C(C(=O)O)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445930>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,1,0,...,6.834109,27.254130,93.982157,11.747770,18,2,16.0,14.0,3.361111,1.333333
64,DMSO,solvent,67-68-5,CS(=O)C,0,<rdkit.Chem.rdchem.Mol object at 0x17d4459a0>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,6.188264,24.179697,78.013936,7.801394,9,0,12.0,9.0,3.111111,1.000000
65,methanol,solvent,67-56-1,CO,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a10>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,1.098612,7.493061,32.026215,5.337702,1,0,2.0,1.0,2.0,1.000000
66,butyltinTrichloride,other,1118-46-3,CCCC[Sn](Cl)(Cl)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a80>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,8.201112,34.881259,281.879178,16.581128,71,5,32.0,30.0,4.8125,1.875000

#### 3. Cleaning of MD full of NAs (remove these columns):

In [64]:
mordred_md = pd.concat([smiles_cleaned, pd.DataFrame(md_df)], axis = 1)
mordred_md

,name,substance_type,CAS_nb,SMILES,detected,molecule,ABC,ABCGG,nAcid,nBase,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,carbaryl,insecticide,63-25-2,CNC(=O)OC1=CC=CC2=CC=CC=C21,1,<rdkit.Chem.rdchem.Mol object at 0x17d35af10>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,9.496496,46.853672,201.078979,7.733807,362,21,74.0,85.0,4.694444,3.472222
1,chlorpyrifos,insecticide,2921-88-2,CCOP(=S)(OCC)OC1=NC(=C(C=C1Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d35b610>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,9.677653,50.667067,348.926284,12.031941,612,26,86.0,97.0,8.256944,4.180556
2,cypermethrine,insecticide,52315-07-8,CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)...,1,<rdkit.Chem.rdchem.Mol object at 0x17d35a490>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,10.344674,84.588084,415.074199,8.831366,2244,39,146.0,172.0,10.201389,6.166667
3,DDD(2-4),insecticide,72-54-8,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359460>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,9.675269,50.806847,317.953661,11.355488,603,26,90.0,103.0,6.666667,4.000000
4,dicofol,insecticide,115-32-2,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)(C(Cl)(Cl)Cl)O)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359e70>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,10.165967,54.227403,367.909603,12.686538,744,35,106.0,126.0,8.569444,4.229167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,tramadol,PPCP,27203-92-5,CN(C)C[C@H]1CCCC[C@@]1(C2=CC(=CC=C2)OC)O,0,<rdkit.Chem.rdchem.Mol object at 0x17d4458c0>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,...,9.918425,52.447194,263.188529,5.981557,670,30,96.0,112.0,7.006944,4.291667
63,chloroacetic acid,solvent,79-11-8,C(C(=O)O)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445930>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,1,0,...,6.834109,27.254130,93.982157,11.747770,18,2,16.0,14.0,3.361111,1.333333
64,DMSO,solvent,67-68-5,CS(=O)C,0,<rdkit.Chem.rdchem.Mol object at 0x17d4459a0>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,6.188264,24.179697,78.013936,7.801394,9,0,12.0,9.0,3.111111,1.000000
65,methanol,solvent,67-56-1,CO,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a10>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,1.098612,7.493061,32.026215,5.337702,1,0,2.0,1.0,2.0,1.000000
66,butyltinTrichloride,other,1118-46-3,CCCC[Sn](Cl)(Cl)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a80>,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,...,8.201112,34.881259,281.879178,16.581128,71,5,32.0,30.0,4.8125,1.875000

In [65]:
## convert df back to numeric (so descriptors with errors can be converted to NAs & then later removed):
mordred_md_num = mordred_md.iloc[:, 5:-1].apply(pd.to_numeric, errors = "coerce")

mordred_md_clean = mordred_md_num.dropna(axis = 1, how = "all")
mordred_md_clean

,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,VE1_A,VE2_A,...,SRW09,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1
0,0,0,19.544560,2.377815,4.755629,19.544560,1.302971,3.627536,3.457764,0.230518,...,0.000000,9.496496,46.853672,201.078979,7.733807,362,21,74.0,85.0,4.694444
1,0,0,20.971017,2.377461,4.754921,20.971017,1.165057,3.775189,3.759106,0.208839,...,0.000000,9.677653,50.667067,348.926284,12.031941,612,26,86.0,97.0,8.256944
2,0,0,34.992970,2.613976,4.943050,34.992970,1.249749,4.277221,3.188891,0.113889,...,8.444838,10.344674,84.588084,415.074199,8.831366,2244,39,146.0,172.0,10.201389
3,0,0,22.540937,2.377662,4.755325,22.540937,1.252274,3.804096,3.839997,0.213333,...,0.000000,9.675269,50.806847,317.953661,11.355488,603,26,90.0,103.0,6.666667
4,0,0,24.107183,2.519762,5.039524,24.107183,1.205359,3.919405,3.804569,0.190228,...,0.000000,10.165967,54.227403,367.909603,12.686538,744,35,106.0,126.0,8.569444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,0,1,24.017666,2.462551,4.925102,24.017666,1.264088,3.859038,3.738528,0.196765,...,0.000000,9.918425,52.447194,263.188529,5.981557,670,30,96.0,112.0,7.006944
63,1,0,5.226252,1.847759,3.695518,5.226252,1.045250,2.408576,2.130986,0.426197,...,0.000000,6.834109,27.254130,93.982157,11.747770,18,2,16.0,14.0,3.361111
64,0,0,3.464102,1.732051,3.464102,3.464102,0.866025,2.178059,1.931852,0.482963,...,0.000000,6.188264,24.179697,78.013936,7.801394,9,0,12.0,9.0,3.111111
65,0,0,2.000000,1.000000,2.000000,2.000000,1.000000,1.407606,1.414214,0.707107,...,0.000000,1.098612,7.493061,32.026215,5.337702,1,0,2.0,1.0,2.000000
66,0,0,8.312845,2.111991,4.223981,8.312845,1.039106,2.911428,2.542011,0.317751,...,0.000000,8.201112,34.881259,281.879178,16.581128,71,5,32.0,30.0,4.812500

In [66]:
## append MD to original df (now that MD are cleaned => rows full of NAs removed):
mordred_df = pd.concat([smiles_cleaned, mordred_md_clean], axis = 1)
mordred_df

,name,substance_type,CAS_nb,SMILES,detected,molecule,nAcid,nBase,SpAbs_A,SpMax_A,...,SRW09,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1
0,carbaryl,insecticide,63-25-2,CNC(=O)OC1=CC=CC2=CC=CC=C21,1,<rdkit.Chem.rdchem.Mol object at 0x17d35af10>,0,0,19.544560,2.377815,...,0.000000,9.496496,46.853672,201.078979,7.733807,362,21,74.0,85.0,4.694444
1,chlorpyrifos,insecticide,2921-88-2,CCOP(=S)(OCC)OC1=NC(=C(C=C1Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d35b610>,0,0,20.971017,2.377461,...,0.000000,9.677653,50.667067,348.926284,12.031941,612,26,86.0,97.0,8.256944
2,cypermethrine,insecticide,52315-07-8,CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)...,1,<rdkit.Chem.rdchem.Mol object at 0x17d35a490>,0,0,34.992970,2.613976,...,8.444838,10.344674,84.588084,415.074199,8.831366,2244,39,146.0,172.0,10.201389
3,DDD(2-4),insecticide,72-54-8,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359460>,0,0,22.540937,2.377662,...,0.000000,9.675269,50.806847,317.953661,11.355488,603,26,90.0,103.0,6.666667
4,dicofol,insecticide,115-32-2,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)(C(Cl)(Cl)Cl)O)Cl,1,<rdkit.Chem.rdchem.Mol object at 0x17d359e70>,0,0,24.107183,2.519762,...,0.000000,10.165967,54.227403,367.909603,12.686538,744,35,106.0,126.0,8.569444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,tramadol,PPCP,27203-92-5,CN(C)C[C@H]1CCCC[C@@]1(C2=CC(=CC=C2)OC)O,0,<rdkit.Chem.rdchem.Mol object at 0x17d4458c0>,0,1,24.017666,2.462551,...,0.000000,9.918425,52.447194,263.188529,5.981557,670,30,96.0,112.0,7.006944
63,chloroacetic acid,solvent,79-11-8,C(C(=O)O)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445930>,1,0,5.226252,1.847759,...,0.000000,6.834109,27.254130,93.982157,11.747770,18,2,16.0,14.0,3.361111
64,DMSO,solvent,67-68-5,CS(=O)C,0,<rdkit.Chem.rdchem.Mol object at 0x17d4459a0>,0,0,3.464102,1.732051,...,0.000000,6.188264,24.179697,78.013936,7.801394,9,0,12.0,9.0,3.111111
65,methanol,solvent,67-56-1,CO,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a10>,0,0,2.000000,1.000000,...,0.000000,1.098612,7.493061,32.026215,5.337702,1,0,2.0,1.0,2.000000
66,butyltinTrichloride,other,1118-46-3,CCCC[Sn](Cl)(Cl)Cl,0,<rdkit.Chem.rdchem.Mol object at 0x17d445a80>,0,0,8.312845,2.111991,...,0.000000,8.201112,34.881259,281.879178,16.581128,71,5,32.0,30.0,4.812500

#### 4. Export results to .csv file:

In [67]:
mordred_df.to_csv("data/mordred_descriptors.csv", index = False)

#### A1. Simple example of Mordred on 3 molecular structures (from SMILES):

https://github.com/mordred-descriptor/mordred/tree/develop/examples

In [24]:
#### 1. ONE MOLECULE + ONE DESCRIPTOR:
from rdkit import Chem

from mordred import Chi, ABCIndex

benzene = Chem.MolFromSmiles('c1ccccc1')

# create descriptor instance
abci = ABCIndex.ABCIndex()

# calculate descriptor value
result = abci(benzene)

print(str(abci), result)

# create descriptor instance with parameter
chi_pc4 = Chi.Chi(type='path_cluster', order=4)

# calculate
result = chi_pc4(benzene)

print(str(chi_pc4), result)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [25]:
#### 2. ONE MOLECULE + MULTIPLE DESCRIPTORS:
from multiprocessing import freeze_support

from rdkit import Chem

from mordred import Chi, ABCIndex, RingCount, Calculator, is_missing, descriptors

if __name__ == "__main__":
    freeze_support()

    benzene = Chem.MolFromSmiles("c1ccccc1")

    # Create empty Calculator instance
    calc1 = Calculator()

    # Register descriptor instance
    calc1.register(Chi.Chi(type="path_cluster", order=4))

    # Register descriptor class using preset
    calc1.register(RingCount.RingCount)

    # Register all descriptors in module
    calc1.register(ABCIndex)

    # Calculate descriptors
    result = calc1(benzene)

    print(result)
    # >>> [0.0, 1, 0, 0, 0, 1, (snip)

    # Calculator constructor can register descriptors
    calc2 = Calculator(Chi.Chi)

    # Descriptors module contains all descriptors
    calc3 = Calculator(descriptors)

    # User can access all descriptor instances by descriptors property
    print(calc3.descriptors)
    # >>> (mordred.EccentricConnectivityIndex.EccentricConnectivityIndex(), (snip)

    # Calculate descriptors
    result = calc3(benzene)

    # get first missing value
    na1 = next(r for r in result if is_missing(r))

    # get reason
    print(na1.error)
    # >>> missing 3D coordinate

    # Delete all missing value
    result = result.drop_missing()

    # convert to dict
    print(result.asdict())

Result({'Xpc-4d': 0.0, 'nRing': 1, 'n3Ring': 0, 'n4Ring': 0, 'n5Ring': 0, 'n6Ring': 1, 'n7Ring': 0, 'n8Ring': 0, 'n9Ring': 0, 'n10Ring': 0, 'n11Ring': 0, 'n12Ring': 0, 'nG12Ring': 0, 'nHRing': 0, 'n3HRing': 0, 'n4HRing': 0, 'n5HRing': 0, 'n6HRing': 0, 'n7HRing': 0, 'n8HRing': 0, 'n9HRing': 0, 'n10HRing': 0, 'n11HRing': 0, 'n12HRing': 0, 'nG12HRing': 0, 'naRing': 1, 'n3aRing': 0, 'n4aRing': 0, 'n5aRing': 0, 'n6aRing': 1, 'n7aRing': 0, 'n8aRing': 0, 'n9aRing': 0, 'n10aRing': 0, 'n11aRing': 0, 'n12aRing': 0, 'nG12aRing': 0, 'naHRing': 0, 'n3aHRing': 0, 'n4aHRing': 0, 'n5aHRing': 0, 'n6aHRing': 0, 'n7aHRing': 0, 'n8aHRing': 0, 'n9aHRing': 0, 'n10aHRing': 0, 'n11aHRing': 0, 'n12aHRing': 0, 'nG12aHRing': 0, 'nARing': 0, 'n3ARing': 0, 'n4ARing': 0, 'n5ARing': 0, 'n6ARing': 0, 'n7ARing': 0, 'n8ARing': 0, 'n9ARing': 0, 'n10ARing': 0, 'n11ARing': 0, 'n12ARing': 0, 'nG12ARing': 0, 'nAHRing': 0, 'n3AHRing': 0, 'n4AHRing': 0, 'n5AHRing': 0, 'n6AHRing': 0, 'n7AHRing': 0, 'n8AHRing': 0, 'n9AHRing': 0, 'n10AHRing': 0, 'n11AHRing': 0, 'n12AHRing': 0, 'nG12AHRing': 0, 'nFRing': 0, 'n4FRing': 0, 'n5FRing': 0, 'n6FRing': 0, 'n7FRing': 0, 'n8FRing': 0, 'n9FRing': 0, 'n10FRing': 0, 'n11FRing': 0, 'n12FRing': 0, 'nG12FRing': 0, 'nFHRing': 0, 'n4FHRing': 0, 'n5FHRing': 0, 'n6FHRing': 0, 'n7FHRing': 0, 'n8FHRing': 0, 'n9FHRing': 0, 'n10FHRing': 0, 'n11FHRing': 0, 'n12FHRing': 0, 'nG12FHRing': 0, 'nFaRing': 0, 'n4FaRing': 0, 'n5FaRing': 0, 'n6FaRing': 0, 'n7FaRing': 0, 'n8FaRing': 0, 'n9FaRing': 0, 'n10FaRing': 0, 'n11FaRing': 0, 'n12FaRing': 0, 'nG12FaRing': 0, 'nFaHRing': 0, 'n4FaHRing': 0, 'n5FaHRing': 0, 'n6FaHRing': 0, 'n7FaHRing': 0, 'n8FaHRing': 0, 'n9FaHRing': 0, 'n10FaHRing': 0, 'n11FaHRing': 0, 'n12FaHRing': 0, 'nG12FaHRing': 0, 'nFARing': 0, 'n4FARing': 0, 'n5FARing': 0, 'n6FARing': 0, 'n7FARing': 0, 'n8FARing': 0, 'n9FARing': 0, 'n10FARing': 0, 'n11FARing': 0, 'n12FARing': 0, 'nG12FARing': 0, 'nFAHRing': 0, 'n4FAHRing': 0, 'n5FAHRing': 0, 'n6FAHRing': 0, 'n7FAHRing': 0, 'n8FAHRing': 0, 'n9FAHRing': 0, 'n10FAHRing': 0, 'n11FAHRing': 0, 'n12FAHRing': 0, 'nG12FAHRing': 0, 'ABC': module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations (ABC), 'ABCGG': module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations (ABCGG/mordred._graph_matrix.DistanceMatrix(False, False, False))})

In [26]:
#### 3. MULTIPLE MOLECULES + MULTIPLE DESCRIPTORS:

from multiprocessing import freeze_support

from rdkit import Chem

from mordred import Calculator, descriptors

if __name__ == "__main__":
    freeze_support()

    mols = [
        Chem.MolFromSmiles("c1ccccc1"),
        Chem.MolFromSmiles("c1ccccc1Cl"),
        Chem.MolFromSmiles("c1ccccc1C"),
    ]

    # Create Calculator
    calc = Calculator(descriptors)

    # map method calculate multiple molecules (return generator)
    print(list(calc.map(mols)))

    # pandas method calculate multiple molecules (return pandas DataFrame)
    print(calc.pandas(mols))

100%|█████████████████████████████████████████████| 3/3 [00:00<00:00,  3.67it/s]

[Result(<rdkit.Chem.rdchem.Mol object at 0x1696eab20>,[<mordred.error.Error object at 0x168e1a3b0>, <mordred.error.Error object at 0x168e1a410>, 0, 0, 8.0, 2.0000000000000004, 4.0, 8.0, 1.3333333333333333, 2.6876239260353, 2.449489742783178, 0.40824829046386296, 0.38505411084803687, 14.696938456699069, 2.4494897427831783, 2.176813580076092, 6, 6, 12, 6, 0, 0, 0, 6, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54.0, 54.0, 54.0, 27.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 36.0, 48.0, 42.0, 18.0, 3.0, 0.0, 0.0, 0.0, 30.0, 36.0, 48.0, 42.0, 18.0, 3.0, 0.0, 0.0, 0.0, 222.0, 252.0, 288.0, 186.0, 42.0, 3.0, 0.0, 0.0, 0.0, 871.68111, 938.2272539999998, 1010.8697819999996, 584.1738029999999, 78.738912, 3.0481920000000002, 0.0, 0.0, 0.0, 2727.6038770815603, 3229.52110871909, 3917.9408069422025, 2833.8925682797944, 874.9221648086934, 93.25123329279079, 0.0, 0.0, 0.0, 85.55387999999999, 87.948888, 130.65468, 148.34391599999998, 83.01657599999999, 20.155392, 0.0, 0.0, 0.0, 68.055, 72.675, 106.335, 115.86750000000002, 62.7, 14.520000000000003, 0.0, 0.0, 0.0, 66.54, 70.5, 103.5, 113.79000000000002, 62.04, 14.520000000000003, 0.0, 0.0, 0.0, 19.401077429093995, 23.414665860000007, 30.09593172, 24.396909149094, 9.348943289093999, 1.3338387145469999, 0.0, 0.0, 0.0, 1870.2720486854942, 1679.5014228174005, 2598.2367090948005, 3327.3595529702948, 2028.2411984228938, 554.7529560727469, 0.0, 0.0, 0.0, 4.5, 4.5, 3.0, 1.2857142857142858, 0.0, 0.0, <mordred.error.Missing object at 0x168e194b0>, <mordred.error.Missing object at 0x168e19270>, <mordred.error.Missing object at 0x168e19630>, 2.5, 3.0, 2.6666666666666665, 2.0, 1.5, 1.0, <mordred.error.Missing object at 0x168e18af0>, <mordred.error.Missing object at 0x168e18bb0>, <mordred.error.Missing object at 0x168e189d0>, 2.5, 3.0, 2.6666666666666665, 2.0, 1.5, 1.0, <mordred.error.Missing object at 0x168e18a30>, <mordred.error.Missing object at 0x168e18550>, <mordred.error.Missing object at 0x168e18580>, 18.5, 21.0, 16.0, 8.857142857142858, 3.5, 1.0, <mordred.error.Missing object at 0x168d1ada0>, <mordred.error.Missing object at 0x168d1bdf0>, <mordred.error.Missing object at 0x168d1a860>, 72.6400925, 78.18560449999998, 56.159432333333314, 27.817800142857138, 6.561576, 1.016064, <mordred.error.Missing object at 0x168d1b8e0>, <mordred.error.Missing object at 0x168d1b7c0>, <mordred.error.Missing object at 0x168d1b610>, 227.30032309013004, 269.12675905992415, 217.6633781634557, 134.9472651561807, 72.91018040072446, 31.083744430930263, <mordred.error.Missing object at 0x168d1bf70>, <mordred.error.Missing object at 0x168d1be80>, <mordred.error.Missing object at 0x168d1b220>, 7.12949, 7.329073999999999, 7.258593333333334, 7.063995999999999, 6.918047999999999, 6.718464, <mordred.error.Missing object at 0x1697559c0>, <mordred.error.Missing object at 0x1697559f0>, <mordred.error.Missing object at 0x169755a20>, 5.671250000000001, 6.0562499999999995, 5.9075, 5.517500000000001, 5.2250000000000005, 4.840000000000001, <mordred.error.Missing object at 0x169755b70>, <mordred.error.Missing object at 0x169755ba0>, <mordred.error.Missing object at 0x169755bd0>, 5.545000000000001, 5.875, 5.75, 5.41857142857143, 5.17, 4.840000000000001, <mordred.error.Missing object at 0x169755d20>, <mordred.error.Missing object at 0x169755d50>, <mordred.error.Missing object at 0x169755d80>, 1.6167564524244995, 1.9512221550000006, 1.6719962066666667, 1.1617575785282857, 0.7790786074244999, 0.44461290484899996, <mordred.error.Missing object at 0x169755ed0>, <mordred.error.Missing object at 0x169755f00>, <mordred.error.Missing object at 0x169755f30>, 155.85600405712452, 139.95845190145005, 144.34648383860002, 158.44569299858546, 169.02009986857448, 184.91765202424895, <mordred.error.Missing object at 0x169756080>, <mordred.error.Missing object at 0x1697560b0>, <mordred.error.Missing object at 0x1697560e0>, 0.04652849888693349, 8.673617379884035e-19, -0.02326424944346675, -0.011632124721733375, -8.673617379884035e-19, 0.011632124721733375, 0.0, 0.0, 0.0, 27.0, 0.0, -13.5, -6.75, 0.0, 6.75, 0.0, 0.0, 0.0, 3.0, 0.0, -1.5, -0.75, 0.0, 0.75, 0.0, 0.0, 0.0, 3.0, 0.0, -1.5, -0.75, 0.0, 0.75, 0.0, 0.0, 0.0, 75.0, 0.0, -37.5, -18.75, 0.0, 18.75, 0.0, 0.0, 0.0, 363.1980269999999, 7.815970093361102e-14, -181.5990134999999, -90.79950675000003, -7.815970093361102e-14, 90.79950674999995, 0.0, 0.0, 0.0, 675.382240317668, 0.0, -337.691120158834, -168.845560079417, 0.0, 168.845560079417, 0.0, 0.0, 0.0, 0.0711479999999999, 0.0, -0.03557399999999996, -0.01778699999999998, 0.0, 0.01778699999999998, 0.0, 0.0, 0.0, 0.36749999999999927, 9.367506770274758e-16, -0.1837499999999987, -0.09187500000000026, -9.367506770274758e-16, 0.09187499999999935, 0.0, 0.0, 0.0, 0.26999999999999974, 7.840950111415168e-16, -0.13499999999999907, -0.06750000000000031, -7.979727989493313e-16, 0.06749999999999952, 0.0, 0.0, 0.0, 3.019272854547, -6.661338147750939e-16, -1.5096364272735006, -0.7548182136367496, 6.661338147750939e-16, 0.7548182136367503, 0.0, 0.0, 0.0, 16.40073806534698, 2.4424906541753444e-14, -8.200369032673468, -4.100184516336757, -2.5757174171303632e-14, 4.100184516336733, 0.0, 0.0, 0.0, 0.0038773749072444578, 7.228014483236696e-20, -0.0012924583024148196, -0.0005539107010349226, -7.228014483236696e-20, 0.003877374907244458, <mordred.error.Missing object at 0x169757670>, <mordred.error.Missing object at 0x1697576a0>, <mordred.error.Missing object at 0x1697576d0>, 2.25, 0.0, -0.75, -0.32142857142857145, 0.0, 2.25, <mordred.error.Missing object at 0x169757820>, <mordred.error.Missing object at 0x169757850>, <mordred.error.Missing object at 0x169757880>, 0.25, 0.0, -0.08333333333333333, -0.03571428571428571, 0.0, 0.25, <mordred.error.Missing object at 0x1697579d0>, <mordred.error.Missing object at 0x169757a00>, <mordred.error.Missing object at 0x169757a30>, 0.25, 0.0, -0.08333333333333333, -0.03571428571428571, 0.0, 0.25, <mordred.error.Missing object at 0x169757b80>, <mordred.error.Missing object at 0x169757bb0>, <mordred.error.Missing object at 0x169757be0>, 6.25, 0.0, -2.0833333333333335, -0.8928571428571429, 0.0, 6.25, <mordred.error.Missing object at 0x169757d30>, <mordred.error.Missing object at 0x169757d60>, <mordred.error.Missing object at 0x169757d90>, 30.26650224999999, 6.5133084111342514e-15, -10.088834083333328, -4.323786035714288, -6.5133084111342514e-15, 30.266502249999984, <mordred.error.Missing object at 0x169757ee0>, <mordred.error.Missing object at 0x169757f10>, <mordred.error.Missing object at 0x169757f40>, 56.281853359805666, 0.0, -18.760617786601888, -8.040264765686524, 0.0, 56.281853359805666, <mordred.error.Missing object at 0x1697600d0>, <mordred.error.Missing object at 0x169760100>, <mordred.error.Missing object at 0x169760130>, 0.0059289999999999924, 0.0, -0.0019763333333333312, -0.000846999999999999, 0.0, 0.005928999999999993, <mordred.error.Missing object at 0x169760280>, <mordred.error.Missing object at 0x1697602b0>, <mordred.error.Missing object at 0x1697602e0>, 0.03062499999999994, 7.806255641895632e-17, -0.01020833333333326, -0.0043750000000000126, -7.806255641895632e-17, 0.03062499999999978, <mordred.error.Missing object at 0x169760430>, <mordred.error.Missing object at 0x169760460>, <mordred.error.Missing object at 0x169760490>, 0.02249999999999998, 6.534125092845973e-17, -0.007499999999999948, -0.003214285714285729, -6.649773324577761e-17, 0.02249999999999984, <mordred.error.Missing object at 0x1697605e0>, <mordred.error.Missing object at 0x169760610>, <mordred.error.Missing object at 0x169760640>, 0.25160607121225, -5.551115123125783e-17, -0.08386869040408336, -0.03594372445889284, 5.551115123125783e-17, 0.2516060712122501, <mordred.error.Missing object at 0x169760790>, <mordred.error.Missing object at 0x1697607c0>, <mordred.error.Missing object at 0x1697607f0>, 1.3667281721122484, 2.0354088784794535e-15, -0.4555760573707482, -0.19524688173032176, -2.146431180941969e-15, 1.3667281721122444, <mordred.error.Missing object at 0x169760940>, <mordred.error.Missing object at 0x169760970>, <mordred.error.Missing object at 0x1697609a0>, 1.8641515603074466e-17, -0.3333333333333334, -0.14285714285714288, -1.8641515603074466e-17, 1.0000000000000002, <mordred.error.Missing object at 0x169757670>, <mordred.error.Missing object at 0x1697576a0>, <mordred.error.Missing object at 0x1697576d0>, 0.0, -0.3333333333333333, -0.14285714285714288, 0.0, 1.0, <mordred.error.Missing object at 0x169757820>, <mordred.error.Missing object at 0x169757850>, <mordred.error.Missing object at 0x169757880>, 0.0, -0.3333333333333333, -0.14285714285714285, 0.0, 1.0, <mordred.error.Missing object at 0x1697579d0>, <mordred.error.Missing object at 0x169757a00>, <mordred.error.Missing object at 0x169757a30>, 0.0, -0.3333333333333333, -0.14285714285714285, 0.0, 1.0, <mordred.error.Missing object at 0x169757b80>, <mordred.error.Missing object at 0x169757bb0>, <mordred.error.Missing object at 0x169757be0>, 0.0, -0.3333333333333333, -0.14285714285714288, 0.0, 1.0, <mordred.error.Missing object at 0x169757d30>, <mordred.error.Missing object at 0x169757d60>, <mordred.error.Missing object at 0x169757d90>, 2.1519858348132227e-16, -0.33333333333333326, -0.14285714285714296, -2.1519858348132227e-16, 0.9999999999999997, <mordred.error.Missing object at 0x169757ee0>, <mordred.error.Missing object at 0x169757f10>, <mordred.error.Missing object at 0x169757f40>, 0.0, -0.3333333333333333, -0.14285714285714288, 0.0, 1.0, <mordred.error.Missing object at 0x1697600d0>, <mordred.error.Missing object at 0x169760100>, <mordred.error.Missing object at 0x169760130>, 0.0, -0.3333333333333334, -0.1428571428571429, 0.0, 1.0000000000000002, <mordred.error.Missing object at 0x169760280>, <mordred.error.Missing object at 0x1697602b0>, <mordred.error.Missing object at 0x1697602e0>, 2.5489814340883746e-15, -0.3333333333333316, -0.14285714285714354, -2.5489814340883746e-15, 0.9999999999999949, <mordred.error.Missing object at 0x169760430>, <mordred.error.Missing object at 0x169760460>, <mordred.error.Missing object at 0x169760490>, 2.9040555968204355e-15, -0.3333333333333313, -0.14285714285714365, -2.955454810923452e-15, 0.9999999999999938, <mordred.error.Missing object at 0x1697605e0>, <mordred.error.Missing object at 0x169760610>, <mordred.error.Missing object at 0x169760640>, -2.2062723273648551e-16, -0.3333333333333335, -0.1428571428571428, 2.2062723273648551e-16, 1.0000000000000004, <mordred.error.Missing object at 0x169760790>, <mordred.error.Missing object at 0x1697607c0>, <mordred.error.Missing object at 0x1697607f0>, 1.489256547140441e-15, -0.33333333333333237, -0.14285714285714327, -1.5704887224390106e-15, 0.999999999999997, <mordred.error.Missing object at 0x169760940>, <mordred.error.Missing object at 0x169760970>, <mordred.error.Missing object at 0x1697609a0>, 0.9166666666666667, 1.2222222222222225, 1.0476190476190477, 0.9166666666666667, 0.0, <mordred.error.Missing object at 0x169761600>, <mordred.error.Missing object at 0x169761630>, <mordred.error.Missing object at 0x169761660>, 0.9166666666666666, 1.222222222222222, 1.0476190476190477, 0.9166666666666666, 0.0, <mordred.error.Missing object at 0x169761780>, <mordred.error.Missing object at 0x1697617b0>, <mordred.error.Missing object at 0x1697617e0>, 0.9166666666666667, 1.2222222222222223, 1.0476190476190477, 0.9166666666666667, 0.0, <mordred.error.Missing object at 0x169761900>, <mordred.error.Missing object at 0x169761930>, <mordred.error.Missing object at 0x169761960>, 0.9166666666666667, 1.2222222222222223, 1.0476190476190477, 0.9166666666666667, 0.0, <mordred.error.Missing object at 0x169761a80>, <mordred.error.Missing object at 0x169761ab0>, <mordred.error.Missing object at 0x169761ae0>, 0.9166666666666666, 1.2222222222222223, 1.0476190476190477, 0.9166666666666666, 0.0, <mordred.error.Missing object at 0x169761c00>, <mordred.error.Missing object at 0x169761c30>, <mordred.error.Missing object at 0x169761c60>, 0.916666666666667, 1.2222222222222225, 1.047619047619048, 0.916666666666667, 0.0, <mordred.error.Missing object at 0x169761d80>, <mordred.error.Missing object at 0x169761db0>, <mordred.error.Missing object at 0x169761de0>, 0.9166666666666666, 1.222222222222222, 1.0476190476190477, 0.9166666666666666, 0.0, <mordred.error.Missing object at 0x169761f00>, <mordred.error.Missing object at 0x169761f30>, <mordred.error.Missing object at 0x169761f60>, 0.9166666666666669, 1.2222222222222225, 1.047619047619048, 0.9166666666666669, 0.0, <mordred.error.Missing object at 0x169762080>, <mordred.error.Missing object at 0x1697620b0>, <mordred.error.Missing object at 0x1697620e0>, 0.9166666666666667, 1.2222222222222223, 1.047619047619048, 0.9166666666666667, 0.0, <mordred.error.Missing object at 0x169762200>, <mordred.error.Missing object at 0x169762230>, <mordred.error.Missing object at 0x169762260>, 0.9166666666666665, 1.2222222222222219, 1.0476190476190472, 0.9166666666666665, 0.0, <mordred.error.Missing object at 0x169762380>, <mordred.error.Missing object at 0x1697623b0>, <mordred.error.Missing object at 0x1697623e0>, 0.9166666666666666, 1.2222222222222223, 1.0476190476190477, 0.9166666666666666, 0.0, <mordred.error.Missing object at 0x169762500>, <mordred.error.Missing object at 0x169762530>, <mordred.error.Missing object at 0x169762560>, 0.9166666666666669, 1.2222222222222223, 1.047619047619048, 0.9166666666666669, 0.0, <mordred.error.Missing object at 0x169762680>, <mordred.error.Missing object at 0x1697626b0>, <mordred.error.Missing object at 0x1697626e0>, 0.30300000000000005, -0.2990000000000001, 3.303000000000003, 2.7009999999999983, 2.303, 1.700999999999999, 2.303, 1.700999999999999, 6.303000000000006, 5.701000000000001, 12.314000000000005, 11.711999999999994, 20.882526276115545, 20.280526276115545, 3.0490000000000013, 2.446999999999998, 2.8529999999999998, 2.2510000000000003, 2.8030000000000017, 2.200999999999998, 1.9729999999999994, 1.3709999999999993, 11.563300000000002, 10.961299999999994, 2.0, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 12.000000000000004, 5.999999999999999, 8.666666666666668, 12.000000000000004, 2.0000000000000004, 6.0090126189062945, 0.0, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 71.96100505779535, 12, 6, 6, 0, 0, 6, 6, 9, 3, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, 0.16666666666666666, 0.16666666666666666, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, <mordred.error.Missing object at 0x169763f40>, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.0, 0.0, 0.037037037037037035, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.242640687119286, 3.0, 2.121320343559643, 1.5, 1.0606601717798214, 0.75, 0.0, 0.0, 0.7071067811865476, 0.5, 0.3535533905932738, 0.25, 0.1767766952966369, 0.125, <mordred.error.Missing object at 0x1697682b0>, <mordred.error.Missing object at 0x1697682e0>, 3.4641016151377544, 1.9999999999999998, 1.1547005383792517, 0.6666666666666667, 0.3849001794597505, 0.2222222222222222, 0.0, 0.0, 0.5773502691896257, 0.3333333333333333, 0.1924500897298753, 0.11111111111111112, 0.06415002990995843, 0.037037037037037035, <mordred.error.Missing object at 0x169768550>, <mordred.error.Missing object at 0x169768580>, 7.000000000000002, 6.503538423112146, 7.625483411357624, 11.663510560815732, 11.176470588235295, 11.280000000000003, 8.395663473053892, 13.245868937772528, 0.5833333333333335, 0.5419615352593455, 0.6354569509464687, 0.971959213401311, 0.931372549019608, 0.9400000000000003, 0.699638622754491, 1.103822411481044, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, <mordred.error.Error object at 0x169768940>, 18.000000000000007, 9.000000000000004, 13.000000000000005, 18.000000000000007, 3.0000000000000013, 9.000420061762544, 2.449489742783177, 0.40824829046386285, 0.38505411084803653, 14.696938456699073, 2.4494897427831788, 2.176813580076092, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

100%|█████████████████████████████████████████████| 3/3 [00:00<00:00,  3.62it/s]

                                                 ABC  \
0  module 'numpy' has no attribute 'float'.\n`np....
1  module 'numpy' has no attribute 'float'.\n`np....
2  module 'numpy' has no attribute 'float'.\n`np....

                                               ABCGG  nAcid  nBase   SpAbs_A  \
0  module 'numpy' has no attribute 'float'.\n`np....      0      0  8.000000
1  module 'numpy' has no attribute 'float'.\n`np....      0      0  8.720566
2  module 'numpy' has no attribute 'float'.\n`np....      0      0  8.720566

    SpMax_A  SpDiam_A    SpAD_A   SpMAD_A   LogEE_A  ...     SRW10     TSRW10  \
0  2.000000  4.000000  8.000000  1.333333  2.687624  ...  7.627057  30.941317
1  2.101003  4.202006  8.720566  1.245795  2.844305  ...  8.124151  33.544698
2  2.101003  4.202006  8.720566  1.245795  2.844305  ...  8.124151  33.544698

           MW       AMW  WPath  WPol  Zagreb1  Zagreb2  mZagreb1  mZagreb2
0   78.046950  6.503913     27     3     24.0     24.0  1.500000  1.500000
1  112.007978  9.333998     42     5     30.0     31.0  2.361111  1.666667
2   92.062600  6.137507     42     5     30.0     31.0  2.361111  1.666667

[3 rows x 1826 columns]